name: Run Tests

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  run_tests:
    name: Run unit tests

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install pnpm
        uses: pnpm/action-setup@v2

      - uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          cache: 'pnpm'

      - name: Install packages
        run: pnpm install

      - name: Run unit tests
        run: pnpm test:unit
